[FEATURE] Supress adding HTTP debug header by extension configuration
xperseguers/t3ext-routing pull request #10
Opened 2016-08-20 08:18 UTC by schams-net

The name of the route is sent as an additional header line in the HTTP response to the client by default. For example:

`X-Causal-Routing-Route: [ExtensionKey] Demo action with a parameter`

Under certain circumstances is not desired.

This feature allows TYPO3 integrators to configure the extension and to supress adding this header line. This can be done in the Extension Manager (which requires admin privileges). The documentation has also been updated to reflect this new feature.

2016-10-16 10:44 UTC, xperseguers requested changes

2016-10-16 10:44 UTC, xperseguers commented on Documentation/Introduction/Index.rst
> +The name of the route is sent as an additional header line in the HTTP response to the client by default:
please just use double colon:

`by default::`

2016-10-16 10:44 UTC, xperseguers commented on Documentation/Introduction/Index.rst
> +..
this needs to be double colons but useless with previous change so just remove this line and the blank one above or below

2016-10-16 10:44 UTC, xperseguers commented on Documentation/Introduction/Index.rst
> +This can be deactivated (supressed) in the extension configuration (Extension Manager).
suPPressed

2016-10-16 10:44 UTC, xperseguers commented on Resources/Private/Language/locallang.em.xlf
> +                <source>Supress HTTP Debug Header:If ticked, the HTTP header X-Causal-Routing-Route is not added</source>
SuPPress

2016-10-16 10:44 UTC, xperseguers commented on Resources/Private/Language/locallang.em.xlf
> +            <trans-unit id="supress_http_debug_header">
here as well

2016-10-16 10:44 UTC, xperseguers commented on Classes/Controller/RoutingController.php
> +            if (is_array($extensionConfiguration) && array_key_exists('supressHttpDebugHeader', $extensionConfiguration)) {
pp for "suppress"

2016-10-16 10:44 UTC, xperseguers commented on Classes/Controller/RoutingController.php
> +            if (is_array($extensionConfiguration) && array_key_exists('supressHttpDebugHeader', $extensionConfiguration)) {
If I'm not misleading, the check for `is_array`, `array_key_exists` and the next one for `1` could be simplified as:

```
if (!empty($extensionConfiguration['suppressHttpDebugHeader']) && $extensionConfiguration['suppressHttpDebugHeader'] === '1') {
```

2016-10-16 10:44 UTC, xperseguers commented on Classes/Controller/RoutingController.php
> +     * @return boolean
```
@return bool
```

I switched from long type name to short to be in line with TYPO3 core

2016-10-16 11:20 UTC, xperseguers commented
another question... what about doing it the other way around with "enable" instead of "disable". By default it will be turned off, which is more secure anyway, and if needed, one may turn it on. Actually that would even be better.

2016-10-17 10:39 UTC, schams-net commented
Yes. I would prefer "disabled by default", too. My understanding is that this feature is predominantly for debugging purposes. Debugging features should not be activated by default as a general rule.

If you agree, I suggest we **drop** this pull request (withdraw) altogether and start a new patch, which disables the HTTP header, but allow administrators to enable it via the Extension Manager (extension configuration).

2016-10-17 11:51 UTC, xperseguers commented
fine with me. thx

2016-10-17 11:51 UTC, closed without merging